export const INSTAGRAM_FEED_STATE_UPDATED = 'INSTAGRAM_FEED_STATE_UPDATED'
export const INSTAGRAM_MEDIA_REQUESTED = 'INSTAGRAM_MEDIA_REQUESTED'
export const INSTAGRAM_IMAGE_SELECTED = 'INSTAGRAM_IMAGE_SELECTED'